version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd frontend-app
      - npm install

  build:
    commands:
      - echo Building the React app...
      - cd react-app
      - npm run build
      - echo Moving build files to site directory...
      - cp -r dist/* ../site/

artifacts:
  files:
    - '**/*'
  base-directory: site
