version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - cd frontend-app
      - npm install

  build:
    commands:
      - echo Building the Next.js app...
      - cd frontend-app
      - npm run build
      - echo Moving build files to site directory...
      - cp -r .next/static ../site/.next/static
      - cp -r public/* ../site/
      - cp .next/BUILD_ID ../site/.next/BUILD_ID
      - cp .next/server/pages/* ../site/

artifacts:
  files:
    - '**/*'
  base-directory: site